[window]
opacity = 0.8

[font]
normal = { family = "Fira Code", style = "Regular" }

[colors.primary]
background = "#162127"

[terminal]
shell = "zsh"

[colors.normal]
magenta = "#df8e6e"
cyan = "#df8e6e"
white = "#a9a6b4"
black = "#09161c"

[colors.bright]
white = "#dddde9"
black = "#554f5a"
