general {
    interval = 1
    colors = true
    color_good = "#3e8fb0"
    color_degraded = "#f6c177"
    color_bad = "#eb6f92"
}

order += "volume master"
order += "battery 0"
order += "cpu_temperature 0"
order += "tztime local"

volume master {
    format = "vol %volume"
    format_muted = "vol mut"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

battery 0 {
    format = "bat %status %percentage (%remaining hr) "
    format_down = ""
    last_full_capacity = true
    integer_battery_capacity = true
    low_threshold = 11
    threshold_type = percentage
    hide_seconds = true
    status_chr = "(+)"
    status_bat = "(-)"
    status_unk = "(?)"
    status_full = "(!)"
}

tztime local {
    format = "%a %m/%d/%y %I:%M:%S %p %Z"
}

