general {
	allow_tearing = false
	border_size = 1

	gaps_in = 5
	gaps_out = 0, 30, 30, 30

	col.active_border = 0xff5e81ac
	col.inactive_border = 0xff4c566a
}

decoration {
	shadow {
		enabled = true
		range = 6
	}
}

cursor {
	no_hardware_cursors = true
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	font_family = Ubuntu Nerd Font
}
