# hyprland config no. 23123123123

# monitors
monitor = DP-1, 2560x1080@200, 0x0, 1
monitor = HDMI-A-1, 1920x1080@100, -1920x0, 1
monitor = DP-2, 1920x1080@100, 2560x0, 1

# execs
exec-once = hyprpaper
exec-once = waybar

# binds
## general
bind = ALT SHIFT, Q,      exit
bind = ALT SHIFT, C,      killactive
bind = ALT SHIFT, space,  togglefloating
bind = ALT      , left,   movefocus, l
bind = ALT      , right,  movefocus, r
bind = ALT      , up,     movefocus, u
bind = ALT      , down,   movefocus, d
## programs
bind = ALT SHIFT, return, exec, alacritty
bind = ALT,       P,      exec, fuzzel
bind = ALT SHIFT, W,      exec, pkill -9 waybar && waybar
## screenshots
bind = ALT CTRL,       S, exec, hyprshot -m region --clipboard-only --freeze
bind = ALT SHIFT CTRL, S, exec, hyprshot -m output --clipboard-only --freeze
bind = ALT SUPER CTRL, S, exec, hyprshot -m window --clipboard-only --freeze
## workspaces
bind = ALT SHIFT, 1, movetoworkspacesilent, 1
bind = ALT SHIFT, 2, movetoworkspacesilent, 2
bind = ALT SHIFT, 3, movetoworkspacesilent, 3
bind = ALT SHIFT, 4, movetoworkspacesilent, 4
bind = ALT SHIFT, 5, movetoworkspacesilent, 5
bind = ALT SHIFT, 6, movetoworkspacesilent, 6
bind = ALT,       1, workspace, 1
bind = ALT,       2, workspace, 2
bind = ALT,       3, workspace, 3
bind = ALT,       4, workspace, 4
bind = ALT,       5, workspace, 5
bind = ALT,       6, workspace, 6
## layout
bind = ALT SHIFT, left,  layoutmsg, swapsplit
bind = ALT SHIFT, right, layoutmsg, swapsplit
bind = ALT SHIFT, up,    layoutmsg, swapsplit
bind = ALT SHIFT, down,  layoutmsg, swapsplit
bind = ALT SHIFT, S,     layoutmsg, togglesplit


# look and feel
## general
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2

    col.active_border = rgb(eeb4b3)
    col.inactive_border = rgb(2f242c)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}
## decorations
decoration {
    rounding = 10
    rounding_power = 2
    
    active_opacity = 1
    inactive_opacity = 0.8

    blur {
        enabled = true
        size = 4
        passes = 3
        popups = true
    }

    layerrule = blur,waybar
}
## animations
animations {
    animation = windows, 1, 5, default, gnomed
    animation = workspaces, 1, 5, default, slidefade
}

# layout
dwindle {
    preserve_split = true
    smart_split = true
}
